name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  # Set environment variables for the entire workflow
  CI: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Create test credentials file
      run: |
        echo "username=Admin" > .creds.env
        echo "password=admin123" >> .creds.env
        echo "incorrectPassword=wrongPassword123" >> .creds.env
        echo "dataFirstName=TestFirstName" >> .creds.env
        echo "dataMiddleName=TestMiddleName" >> .creds.env
        echo "dataLastName=TestLastName" >> .creds.env
        
    - name: Run Playwright tests
      run: npx playwright test --reporter=github
      
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30
